export const siteConfig = {
  name: 'MobDeals Kenya',
  shortName: 'MobDeals',
  locale: 'en-KE',
  siteUrl: 'https://shop.mobdeals.co.ke',
  marketingUrl: 'https://mobdeals.co.ke',
  defaultTitle: 'Electronics in Nairobi | MobDeals Kenya',
  defaultDescription: 'Shop laptops, printers, monitors, tablets and electronics from MobDeals Kenya. Nairobi store, warranty support and countrywide delivery.',
  defaultImage: '/images/og-default.jpg',
  logo: '/images/logo.png',
  themeColor: '#102A2A',
  twitterHandle: '',
  whatsappNumber: '254701499849',
  phone: '+254 701 499 849',
  phoneHref: 'tel:+254701499849',
  email: 'support@mobdeals.co.ke',
  address: 'Moi Avenue, Nairobi CBD',
  openingHours: 'Contact us to confirm opening hours.',
  directionsUrl: 'https://www.google.com/maps/search/?api=1&query=Moi%20Avenue%2C%20Nairobi%20CBD',
  storageBucket: 'product-images',
  supabaseUrl: import.meta.env.PUBLIC_SUPABASE_URL,
  supabaseAnonKey: import.meta.env.PUBLIC_SUPABASE_ANON_KEY
} as const;
